version: '3.9'

services:
  
  webapi:
    image: ${DOCKER_REGISTRY-}demowebapp1
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Str0ngPa$$w0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql-demo:/var/opt/mssql

volumes: 
  mssql-demo:
    external: true
